name: macOS
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install Dependencies
        run: |
          brew install create-dmg dylibbundler gtk+3
      - name: Build
        run: |
          python3 grabTitles.py
          go build -ldflags="-s -w" ./cmd/downloadall
      - name: Package
        run: |
          python3 data/create_bundle.py
          mkdir -p out/WiiUDownloader.app/Contents/Resources/lib/share/glib-schemas
          cp $(brew --prefix)/share/glib-2.0/schemas/* out/WiiUDownloader.app/Contents/Resources/lib/share/glib-schemas
          sudo codesign --force --sign -  out/WiiUDownloader.app
          create-dmg \
            --volname "WiiUDownloader" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "WiiUDownloader.app" 200 190 \
            --hide-extension "WiiUDownloader.app" \
            --app-drop-link 600 185 \
            "WiiUDownloader-macOS-Universal.dmg" \
            "out/"
      - name: Upload macOS Artifact
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: True
          makeLatest: True
          omitBody: True
          omitBodyDuringUpdate: True
          omitNameDuringUpdate: True
          artifacts: "WiiUDownloader-macOS-Universal.dmg"
          token: ${{ secrets.GITHUB_TOKEN }}
