name: MSYS2
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

env:
  GOPROXY: direct

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          release: true
          update: true
          install: zip git mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-python mingw-w64-ucrt-x86_64-gtk3 mingw-w64-ucrt-x86_64-pkg-config mingw-w64-ucrt-x86_64-go mingw-w64-ucrt-x86_64-ntldd-git make
      - name: Build
        run: |
          python3 grabTitles.py
          go build -ldflags="-s -w" ./cmd/downloadall
      - name: Deploy WiiUDownloader
        run: |
          mkdir dist
          cp downloadall.exe dist/downloadall.exe
          cd dist && zip -9 -r ../WiiUDownloader-Windows.zip .
      - name: Upload Windows Artifact
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: True
          makeLatest: True
          omitBody: True
          omitBodyDuringUpdate: True
          omitNameDuringUpdate: True
          artifacts: "WiiUDownloader-Windows.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
